### ISSUE TITLE
Trouble installing on Ubuntu 14.04

### ISSUE THREAD

**Issue by olafleur** [pothibo/ecrire#130]
I have now installed ruby, rbenv, bundler and rails.

I've created my blog with the command ```ecrire new monblog```
But when I run ```ecrire server``` it tells me 
```The path `/home/ubuntu/Develop/ecrire` does not exist.```

I've created said repository and do a bundle install in the ```monblog``` directory.

Now I have this error message:
```Could not find gem 'ecrire (>= 0) ruby' in source at ~/Develop/ecrire.
Source does not contain any versions of 'ecrire (>= 0) ruby'```

So, it expects the gem to be in the ```Develop``` directory?

At the moment, when I run ```gem environment``` I have this in the output:
```  
- GEM PATHS: 

     - /home/ubuntu/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0 

     - /home/ubuntu/.gem/ruby/2.2.0
```

Should I change/add a gem path?

Maybe it's not configured to be installed on Ubuntu, but I would really like to run it on Ubuntu, if possible. It seems like a cool tool. ;-)

Do you have any idea of what I could do to make it run there?

Thanks a lot!

**Comment by pothibo** [comment]
Ok, it seems I accidently put a Development gemfile on master, let me fix that real quick ;)

**Comment by pothibo** [comment]
To fix this issue,  you can do one of the following things:

#### Upgrade your gem and restart

I just published a new hotfix version on rubygems so you could just do ```gem update ecrire``` and then recreate a blog using the command you used. The Gemfile should be good to go this time.


### Modify your Gemfile

Open the Gemfile in your blog folder and change the line
```ruby
gem 'ecrire', path: '~/Develop/ecrire'
```

to

```ruby
gem 'ecrire', git: 'https://github.com/pothibo/ecrire.git'
```

And then type ```bundle update``` which should fix this shameful issue :(

**Comment by olafleur** [comment]
Great, now it works in local, thanks!

However, now I am not able to access it from an external computer.

For example, when I access ```localhost:3000``` I get the content.

However, when I access ```xxx.xxx.xxx.xxx:3000``` where xxx.xxx.xxx.xxx is the IP of my machine, the access is not allowed.

I know that it's not a problem with the configuration of the ports of my server, because when I run something else on port 3000, it works just fine.

Any idea?

**Comment by olafleur** [comment]
Should I open another issue for that or it's just me that does not get the app configuration right? ;-)

**Comment by pothibo** [comment]
Yes, this is a known issue which is somewhat low priority as I don't really need that feature. I'm pretty sure it's very easy to fix however as I believe Rails does it out of the box, so it's just a matter of bridging Ecrire to Rails.

If you could open a new issue, that'd be great! Pull Request are also welcome if you get to know why it's not working ;)

**Comment by olafleur** [comment]
Ok. Will open another issue.

Honestly, I am not that familiar with Ruby and Rails, but I may try to give it a try if I got some time. ;-)
