### ISSUE TITLE
Unable to access ecrire from an external access.

### ISSUE THREAD

**Issue by olafleur** [pothibo/ecrire#132]
I am not able to access to the ecrire application from an external computer.

For example, when I access localhost:3000 I get the content.

However, when I access xxx.xxx.xxx.xxx:3000 where xxx.xxx.xxx.xxx is the IP of my machine, the access is not allowed.

I know that it's not a problem with the configuration of the ports of my server, because when I run something else on port 3000, it works just fine.

Answer from @pothibo in #130 : "Yes, this is a known issue which is somewhat low priority as I don't really need that feature. I'm pretty sure it's very easy to fix however as I believe Rails does it out of the box, so it's just a matter of bridging Ecrire to Rails."

**Comment by pothibo** [comment]
Alright, so I believe that Rails support this feature. My take is that there is an option that is not passed down to Rails when loading the server.

As a reference, ```ecrire server``` is a method that wraps around [```rails server```](https://github.com/rails/rails/blob/master/railties/lib/rails/commands/server.rb)

Maybe the reverselookup option is not set... Not sure if it's there from Rails 5 (Master is Rails 5).

**Comment by olafleur** [comment]
From what I understand by looking quickly, if we bind the ```-b``` parameter of ```rails server``` to the IP of the machine it should work.

**Comment by pothibo** [comment]
The -b parameter is also required when using a docker container so this might be important to fix.
