### ISSUE TITLE
Out of focus problem

### ISSUE THREAD

**Issue by Drbelfast** [pothibo/ecrire#161]
I found when I tried to type `##` and enter space, the caret will disappear and have to use mouse to click again to find my input position. It's not a big issue, but could be annoying sometimes.  My guess is when replacing `<p>` with `<h1>`, it didn't reset the caret. Any ideas?

**Comment by pothibo** [comment]
Hmm, what browser are you using? It shouldn't leave focus.

**Comment by Drbelfast** [comment]
@pothibo chrome Version 49.0.2623.87.  on mac OSX 10.10.4

**Comment by pothibo** [comment]
I have the very same version and this isnt' happening to me. I'll look at it tonight as I find this troubling :)

**Comment by Drbelfast** [comment]
@pothibo  I created a [git](http://drbelfast.github.io/issues/ecrire/), to help your better understanding :)

**Comment by pothibo** [comment]
Thank you very much! Does this happen only in this scenario or every time you create a new header?

**Comment by Drbelfast** [comment]
@pothibo It seems not only limited to headers. It happens to all of them. But one or two times out of ten, I can keep my caret in the right place.(and can't reproduce it) Is this weird to you? I tested using the online demo you provided. Shouldn't be my build problem.

**Comment by pothibo** [comment]
This could be a racing condition that I haven't seen before. This gives me an idea to look for. Thank you!

**Comment by pothibo** [comment]
Ok I have a more recent version of OS X but the very same version of Chrome. I went and typed on the editor and I have no issues whatsoever. This is bugging me so hard. Do you have an extension that you use like Adblocker or something? Could you look at the console and tell me if there's any JS error in there?

**Comment by Drbelfast** [comment]
Yeah, you are right. I disabled extensions one by one and found the evil is `Evernote Web Clipper` . The editor worked as I turned it off.
The version is 6.7.1 from chrome app store.

**Comment by pothibo** [comment]
Thank you for clarifying the issue with me. I'll keep this bug open a little longer just so I can test out if there's a way to fix it for you. However, I might not be able due to the way plugin inject themselves into pages. I'll keep you updated on my finding

**Comment by pothibo** [comment]
Since the Editor is now outside of Ecrire, I should close this issue. Feel free to reopen it @ https://github.com/pothibo/written if you have it. (Written has seen a lot of updates so I doubt it still is relevant)
