### ISSUE TITLE
After creating a post it doesn't save to database properly due to this error

### ISSUE THREAD

**Issue by joshkoo** [pothibo/ecrire#165]
Showing /usr/local/rvm/gems/ruby-2.3.0/gems/ecrire-0.31.1/lib/ecrire/app/views/admin/posts/edit.html.erb where line #42 raised:

undefined method `[]' for nil:NilClass

href: admin_post_path(@post.id) do |div|

          **namespace = Pathname.new(Rails.application.secrets.s3['namespace'] || '') ## Highlighed line**

          if Rails.application.secrets.has_key?(:s3)
            div['data-bucket'] = Rails.application.secrets.s3['bucket']

I really want to test this blog engine and would like to use it to create an only blog website not added to an existing rails app. Should i create a s3 bucket to store post data? or may i use it without having one.

Thank you

**Comment by pothibo** [comment]
Thank you for testing it out!

It seems like I'm not checking if the secrets are set. This is something that can easily be fix, I should be able to do it either tonight (EST) or tomorrow

**Comment by pothibo** [comment]
This error was already fixed on master and I had not released the gem with the fix. I just did it so a simple bundle update should suffice. Let me know if you have any other issue with Ecrire :D

**Comment by Chenclech** [comment]
Thanks for the update.

/usr/local/rvm/gems/ruby-2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require': cannot load such file -- autoprefixer-rails (LoadError)

I got this error after the uodate when trying to run server, however i am not sure if it is something with the update or my system i will try a clean install later on and let you know.
